name: covid
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - python=3.7.7
  - pandas
  - ipywidgets
  - Ipython
  - voila
  - pip:
    - colorlover==0.3.0
    - cufflinks==0.17.3
#prefix: /Users/jhao/anaconda3/envs/covid

