name: covid
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas
  - ipywidgets
  - Ipython
  - voila
  - scipy
  - pip:
    - colorlover
    - cufflinks
#prefix: /Users/jhao/anaconda3/envs/covid

